server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

jwt:
  secret: 022a742e-936c-4a28-9a97-db6c16a98e5e
  expiration-in-milliseconds: 30_000

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false